spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    url: jdbc:sqlite:sqlite/db.sqlite

mybatis:
  # mybatis xml配置路径
  mapper-locations: classpath:mybatis/*.xml

# 日志级别
logging:
  level:
    com:
      rrr:
        performanceidx:
          dao: debug
